# Generated by Django 2.2.5 on 2020-02-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
