# Generated by Django 2.2.5 on 2020-02-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200218_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='settingsRound',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='session',
            name='settingsTime',
            field=models.IntegerField(blank=True, default=1200),
        ),
    ]
