# Generated by Django 2.2.5 on 2020-02-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_building_centerterritory_leftterritory_rightterritory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='tittle',
        ),
        migrations.AddField(
            model_name='building',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
