# Generated by Django 2.2.5 on 2020-02-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200224_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='subordinate',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='session',
            name='settingCorn',
            field=models.IntegerField(blank=True, default=2000),
        ),
        migrations.AddField(
            model_name='session',
            name='settingsSubordinate',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AddField(
            model_name='session',
            name='settingsWarrior',
            field=models.IntegerField(blank=True, default=500),
        ),
    ]
